# Generated by Django 4.0.6 on 2022-07-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(max_length=3000, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
                ('User_pwd', models.CharField(max_length=200)),
                ('User_email', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Post_links', models.URLField(max_length=300)),
                ('post_information', models.CharField(max_length=200)),
                ('post_links_videos', models.URLField(max_length=300)),
                ('post_links_photos', models.URLField(max_length=300)),
                ('time', models.DateTimeField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.user')),
                ('subreddit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit')),
            ],
        ),
        migrations.AddField(
            model_name='subreddit',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.user'),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.user')),
                ('subreddit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('Thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.threads')),
            ],
        ),
    ]
