# Generated by Django 4.0.6 on 2022-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0007_posts_unlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
